name: Deploy to producction

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
          
      - name: Update and Upgrade ubuntu
        run: | 
          sudo apt-get update
          sudo apt-get upgrade  

      - name: Show files
        run: ls -a
        
      - name: Clean project
        run: mvn clean     

      - name: Compile jar
        run: mvn package

      - name: Run tests
        run: mvn test
        
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "workflow-test-main" 
          heroku_email: "kevin.cancimanse@correounivalle.edu.co"
          remote_branch: "main"
